input.onButtonPressed(Button.A, function () {
    kitronik_air_quality.show("Enregistrement...", 1, kitronik_air_quality.ShowAlign.Left)
    for (let index = 0; index < 60; index++) {
        kitronik_air_quality.logData()
        kitronik_air_quality.setDataForUSB()
        kitronik_air_quality.selectSeparator(kitronik_air_quality.Separator.tab)
        kitronik_air_quality.includeDate()
        kitronik_air_quality.includeTime()
        kitronik_air_quality.includeTemperature(kitronik_air_quality.TemperatureUnitList.C)
        kitronik_air_quality.includePressure(kitronik_air_quality.PressureUnitList.Pa)
        kitronik_air_quality.includeHumidity()
        kitronik_air_quality.includeIAQ()
        kitronik_air_quality.includeCO2()
        basic.pause(60000)
    }
    kitronik_air_quality.clearLine(1)
    kitronik_air_quality.show("Enregistrement terminé!", 1, kitronik_air_quality.ShowAlign.Right)
})
input.onButtonPressed(Button.AB, function () {
    kitronik_air_quality.clearLine(1)
    kitronik_air_quality.show("Effacement des donnees...", 1, kitronik_air_quality.ShowAlign.Left)
    kitronik_air_quality.eraseData()
    kitronik_air_quality.show("Effacement termine!", 1, kitronik_air_quality.ShowAlign.Right)
    basic.pause(5000)
    kitronik_air_quality.clearLine(1)
})
input.onButtonPressed(Button.B, function () {
    kitronik_air_quality.clearLine(1)
    kitronik_air_quality.show("Transfert des donnees...", 1, kitronik_air_quality.ShowAlign.Left)
    kitronik_air_quality.sendAllData()
    kitronik_air_quality.show("Transfert termine!", 1, kitronik_air_quality.ShowAlign.Right)
})
kitronik_air_quality.setTime(20, 31, 0)
kitronik_air_quality.setDate(6, 4, 23)
kitronik_air_quality.addProjectInfo("AIRquality", "Local_107")
kitronik_air_quality.setupGasSensor()
kitronik_air_quality.calcBaselines()
basic.forever(function () {
    kitronik_air_quality.measureData()
    kitronik_air_quality.show("T:" + kitronik_air_quality.readTemperature(kitronik_air_quality.TemperatureUnitList.C) + " C", 3, kitronik_air_quality.ShowAlign.Left)
    kitronik_air_quality.show("P:" + kitronik_air_quality.readPressure(kitronik_air_quality.PressureUnitList.Pa) + " Pa", 4, kitronik_air_quality.ShowAlign.Left)
    kitronik_air_quality.show("H:" + kitronik_air_quality.readHumidity() + " %", 5, kitronik_air_quality.ShowAlign.Left)
    kitronik_air_quality.show("IAQ:" + kitronik_air_quality.getAirQualityScore(), 6, kitronik_air_quality.ShowAlign.Left)
    kitronik_air_quality.show("eCO2:" + kitronik_air_quality.readeCO2() + " ppm", 7, kitronik_air_quality.ShowAlign.Left)
    basic.pause(5000)
})
